### PR TITLE
Fixes issue with broadcasting non ascii characters (fixes #6)

### LINKED ISSUE #6: Broadcasting non ascii characters
I had a problem broadcasting non ascii characters (Greek names)
I fixed it by changing 
in ServerAdvertiser.gd line 30
`var packet := packetMessage.to_ascii()`
to
`var packet := packetMessage.to_utf8()`

and in ServerListener line 40
`var serverMessage = array_bytes.get_string_from_ascii()`
to
`var serverMessage = array_bytes.get_string_from_utf8()`

According to Godot Docs

```
String get_string_from_utf8()

Returns a copy of the array's contents as String. Slower than get_string_from_ascii() but supports 
UTF-8 encoded data.
Use this function if you are unsure about the source of the data.
For user input this function should always be preferred.

### PR DESCRIPTION
**Pull request by ThomasT75**
If something is not ok don't hesitate to tell me

### CODE REVIEW

**Comment by Wavesonics** [comment]
could you maybe pair this back to the minimal change set? There's a lot of import changes and formatting

**Comment by mageowl** [comment]
this fixes #6.

**Comment by mageowl** [comment]
Could we turn this into an option to minimize the packet size?

**Comment by ThomasT75** [comment]
Yes it took this long for me to fix github notifications and get common sense enjoy the fix for #6

**Pull request merged**
